
services:
  # Servicio para la base de datos PostgreSQL (usuarios)
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: contrasena
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - ./database/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ecommerce-net

  # Servicio para la base de datos MySQL (productos)
  mysql-db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  
      MYSQL_DATABASE: ecommerce  
    ports:
      - "3307:3306"
    volumes:
      - ./database/mysql/init-products.sql:/docker-entrypoint-initdb.d/init-products.sql
    networks:
      - ecommerce-net

  # Servicio de autenticación para los usuarios (auth-service)
  auth-service:
    build: ./backend/auth-user-service
    ports:
      - "3001:3001"
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=contrasena
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=ecommerce
    depends_on:
      - database
    networks:
      - ecommerce-net

  # Servicio de productos (product-service)
  product-service:
    build: ./backend/product-service
    ports:
      - "3002:3002"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword  
      - MYSQL_HOST=mysql-db
      - MYSQL_PORT=3306  
      - MYSQL_DB=ecommerce  
    depends_on:
      - mysql-db
    networks:
      - ecommerce-net

  # Servicio adicional para guardar usuarios en YAML (user-logger)
  user-logger:
    build: ./backend/user-logger
    environment:
      - DB_USER=postgres
      - DB_PASSWORD=contrasena
      - DB_HOST=database
      - DB_PORT=5432
      - DB_NAME=ecommerce
    restart: always
    volumes:
      - ./frontend/users-output:/output   # Carpeta para almacenar el archivo YAML
    depends_on:
      - database
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge

volumes:
  logs:
